### PR TITLE
Add support for notional orders

### PR DESCRIPTION
**Pull request by behos**
Draft pull request to add support for Notional orders.

This is still WIP and created to track the necessary changes to add support for notional orders.

### CODE REVIEW

**Comment by d-e-s-o** [comment]
Thanks for the pull request! Overall it looks good to me. However, I'd rather we have an `Amount` *replace* the existing quantity in `OrderReq`, instead of having `quantity` and `notional` side-by-side (both of which cannot be used at the same time as per the API documentation). That will also eliminate the `skip_serializing_if` constructs.

**Comment by behos** [comment]
> Thanks for the pull request! Overall it looks good to me. However, I'd rather we have an `Amount` _replace_ the existing quantity in `OrderReq`, instead of having `quantity` and `notional` side-by-side (both of which cannot be used at the same time as per the API documentation). That will also eliminate the `skip_serializing_if` constructs.

I agree with both points. I made the related changes and added some tests around this.

I'd rather not reset my paper account for the integration tests. Is there a way to trigger the CI pipeline for this PR?

**Comment by behos** [comment]
I finally had a chance to try this out on my paper account and (perhaps surprisingly) notional orders work.

I also tried out the API calls you added to the https://github.com/alpacahq/Alpaca-API/issues/191 issue and they work for me as well :confused: 

There must be some inconsistency in the configuration of our paper accounts.

On another note, fractional `qty` works too so I'm updating the PR to match and pulling in the tests you added in `topic/ci` branch.

Perhaps grasping at straws, buy could you try disabling and re-enabling the fractional trading setting in your config?

**Comment by behos** [comment]
Done! All the relevant tests are passing for my account. I squashed again to fix up the commit message and remove some back and forth in the process.

**Comment by d-e-s-o** [comment]
> I finally had a chance to try this out on my paper account and (perhaps surprisingly) notional orders work.

Oh wow. I've toggled all account settings in both the live and paper account but nothing changed for me. Also, I am not even using the same paper account in CI, so that's another paper account with the same problem. Will reach out to support.

> Done! All the relevant tests are passing for my account. I squashed again to fix up the commit message and remove some back and forth in the process.

Awesome, thanks! I think merging will have to wait until this issue is resolve, though. I don't really want to have a failing test everywhere. Will ping them.

**Comment by d-e-s-o** [comment]
So I was advised to reset the paper account(s) (true story...) and now it seems to be working. That means tomorrow we may be able to move forward.

**Comment by d-e-s-o** [comment]
Fantastic work, I merged the patch with minor changes. Thanks for your contribution! The functionality will be included in the next release.

**Comment by behos** [comment]
Great! Thanks for the ideas and help throughout 🙂

**Pull request closed without merging**
