### PR TITLE
Add Display to a few Order Types; Add new TimeInForce variants 

### PR DESCRIPTION
**Pull request by ajmwagar**
The Alpaca API recently updated to support Fill Or Kill (fok) and Immediate Or Cancel (ioc) variants for TimeInForce.

I also added std::fmt::Display to most Order sub-types. (note: I used pattern matching, there may exist a trivial way to do this using Serde's renamed values.)

### CODE REVIEW

**Comment by d-e-s-o** [comment]
Thanks for the pull request! May I ask what you need the display implementation for? I am reluctant to provide one, as the output is mostly a policy thing. I'd be more willing to provide the output via a `Debug` implementation.

The Fill Or Kill (fok) and Immediate Or Cancel (ioc) stuff is fine, but can you please create a separate commit? Also, should come with a test, but I can add that as well.

**Comment by ajmwagar** [comment]
Sure! I'm using the Display impl to display the items at Prometheus metrics. 

image

It's pretty clean if I can just call `.to_string()` on your fields.

---

I'm happy to split out the ioc/fok stuff and clean it up a bit.

**Comment by d-e-s-o** [comment]
Sounds good! Okay, so would a `Debug` implementation that reports the same strings suffice then as well? You can always create your own `to_string` function that just forwards to `format("{:?}", val)`.

**Comment by ajmwagar** [comment]
Debug would work. I'm heading off for the night so I'll contribute more tomorrow.

Thanks for the feedback.

**Comment by ajmwagar** [comment]
I'll get this done today or tomorrow. Some stuff came up at work that has had me slammed.

**Comment by d-e-s-o** [comment]
Closing due to inactivity.

**Pull request closed without merging**
