### PR TITLE
Add support for historical data v2 APIs

### PR DESCRIPTION
**Pull request by behos**

### CODE REVIEW

**Review by d-e-s-o — COMMENTED** [review]
Looks great to me! Thanks for working on it and for adding tests! Is there a reason to write custom serialization routines as opposed to just tagging the members with `#[serde(rename ...)]` and deriving `Serialize`, though? It seems like a bunch of unnecessary code.

**Comment by behos** [comment]
> Looks great to me! Thanks for working on it and for adding tests! Is there a reason to write custom serialization routines as opposed to just tagging the members with `#[serde(rename ...)]` and deriving `Serialize`, though? It seems like a bunch of unnecessary code.

You are right :man_facepalming: 
I updated it now :)

**Comment by d-e-s-o** [comment]
Thank you! Will take another look and merge tomorrow.

**Comment by d-e-s-o** [comment]
Merged. Thanks for getting this done! The only thing that is not super great is that apparently Alpaca supports customizable time frames. That is, instead of only 1 minute, 1 hour, and 1 day it seems these are actually partly free-form and support something like `15Min` as well. I've never been a big fan of that with Polygon, but yeah it seems to be a possibility...

**Pull request closed without merging**
