### PR TITLE
Add order_class to the parsed order response.

### PR DESCRIPTION
**Pull request by husafan**
https://alpaca.markets/docs/api-references/trading-api/orders/

### CODE REVIEW

**Review by d-e-s-o — APPROVED** [review]
Seems fine to me. Thanks! Will merge after the markets open next.

**Comment by d-e-s-o** [comment]
> Seems fine to me. Thanks! Will merge after the markets open next.

Actually, nevermind; I merged it now.

**Comment by husafan** [comment]
Thank you!

What is the typical process for releasing the crate and how long does that take? I was hoping to use this change from apcacli to print the order type in the CLI output. No rush, just curious.

**Comment by d-e-s-o** [comment]
> What is the typical process for releasing the crate and how long does that take? I was hoping to use this change from apcacli to print the order type in the CLI output. No rush, just curious.

There is no fixed timeline. Once the subjective measure of "sufficient changes to justify a release" has been reached it will happen. The barrier for patch releases (compatibility preserving) is typically much lower. Right now this is the only change we have for the next release. What's worse, this change is compatibility breaking. We can accelerate if there is a need, though. It's just a hassle for everyone if every commit were to create a new minor release that requires a bump in downstream code.

**Comment by husafan** [comment]
Nope, no need to accelerate anything. And thank you for taking the time to explain. I have both branches locally and can use my versions for development and testing. When I see the new version, I'll send another pull request for apcacli. In the meantime, are there any issues you want help with on apca?

**Comment by d-e-s-o** [comment]
> In the meantime, are there any issues you want help with on apca?

Some ideas that I have on my TODO list are the following:
- unify the way we create dates in tests? e.g., see commit "Add test for retrieval of aggregate bars for non-existent symbol"
- does rate limit set `Retry-After` header? If so we need to expose its value
- hook up portfolio history: https://github.com/alpacahq/user-docs/commit/5a08ba4b20d4132ff269790260b7f32348cdc2a0
- hook up news API
- can we support gzipped historical data? (https://github.com/alpacahq/user-docs/pull/164/commits/9502318785eacf2176285f210ef4bcc172b6a3e4)
- support OAUTH? (https://alpaca.markets/learn/connecting-to-oauth/)

Since you were also looking into `apcacli`:
- don't use colors when input is not a TTY

Some of them may be significantly more involved than others; I've ordered them roughly by increasing anticipated complexity. Some are mostly investigative at this point and further work will depend on the outcome of the investigation. Happy to provide more context if you feel that something piques your interest, in which case I'd suggest you open a quick issue to discuss some more.

**Comment by husafan** [comment]
This is extremely helpful. I will work on these with you. Thanks!

**Comment by d-e-s-o** [comment]
Hm, only noticing now that this member should have been called `class` instead of `order_class` :-| Will fix it up. Luckily we haven't cut a release yet.

**Pull request closed without merging**
